export const STORAGE_KEYS = {
  gatewaySettings: "mc-gateway-settings",
  gatewayUrlHistory: "mc-gateway-url-history",
  gatewayTokenFallback: "mc-gateway-token",
  density: "mc-density",
  themeName: "mc-theme-name",
  themeMode: "mc-theme-mode",
  cockpitPagesV1: "mc-cockpit-pages-v1",
  cockpitPagesV2: "mc-cockpit-pages-v2",
  cockpitPagesV3: "mc-cockpit-pages-v3",
  onboardingDismissedAtMs: "mc-onboarding-dismissed-at-ms",
  guidedTourCompletedV1: "mc-guided-tour-completed-v1",
  assistantCorePromptV1: "mc-assistant-core-prompt-v1",
  opsUxRuntimeConfigV1: "mc-opsux-runtime-v1",
  liveFeedRecoveryV1: "mc-live-feed-recovery-v1",
} as const;
